config/routes.rb
Rails.application.routes.draw do
  get 'games/update_data' => 'games#update_data'
  resources :games, only: [:index, :show]

  root 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :channels

  def self.delete_data
    Channel.delete_all
  end

  def self.update_data
    require "importio"
    client = Importio.new("c676d33a-07d7-46ef-8d08-a6920ea7daf6", "ToGGkRNT60bqadUUNW66knixXKB9uw8HwHCIDTQz8ocY1OBklyKXesXgYX1yUFooW4sMYgEG4WBqaTsQuT8j5w==")
    client.connect
    data_rows = []

    callback = lambda do |query, message|
      # Disconnect messages happen if we disconnect the client library while a query is in progress
      if message["type"] == "DISCONNECT"
        puts "The query was cancelled as the client was disconnected"
      end
      if message["type"] == "MESSAGE"
        if message["data"].key?("errorType")
          # In this case, we received a message, but it was an error from the external service
          puts "Got an error!"
          puts JSON.pretty_generate(message["data"])
        else
          # We got a message and it was not an error, so we can process the data
          puts "Got data!"
          #puts JSON.pretty_generate(message["data"])
          # Save the data we got in our dataRows variable for later
          data_rows << message["data"]["results"]
        end
      end
      if query.finished
        puts "Query finished"
      end
    end

    douyu_urls = ["http://www.douyutv.com/directory/game/CF", "http://www.douyutv.com/directory/game/How", "http://www.douyutv.com/directory/game/LOL", "http://www.douyutv.com/directory/game/DOTA2", "http://www.douyutv.com/directory/game/WOW"]
    game17173_urls = ['http://v.17173.com/live/game/421','http://v.17173.com/live/game/1137','http://v.17173.com/live/game/21', 'http://v.17173.com/live/game/2007', 'http://v.17173.com/live/game/1589']

    #client.query({"input"=>{"query"=>"server"},"connectorGuids"=>dota_uuids}, callback)
    douyu_urls.each do |url|
      client.query({"input"=>{"webpage/url"=>url},"connectorGuids"=>["002249e6-3a8e-4181-ab71-7c8cf7728ee2"]}, callback)
    end
    game17173_urls.each do |url|
      client.query({"input"=>{"webpage/url"=>url},"connectorGuids"=>["1efc0b47-5f9a-4bd4-abf2-53b1d5f9e302"]}, callback)
    end


    puts "Going to join"
    client.join
    puts "Join completed"
    puts "Going to disconnect"
    client.disconnect
    puts "Disconnected"

    # Channel.delete_alla
    #all_live_channels.update_all(status: false)
    update_begin_time = Time.now

    data_rows.each do |datas|
      datas.each do |data|
        channel = Channel.find_by(link: data['link'])
        vs = get_viewers(data['viewers'])
        if channel
          channel.update(title: data['title'], viewers: vs, image: data['image'], status: true)
        else
          game = Game.find_by(name: data['type'])
          game.channels.create(title: data['title'], viewers: vs, link:data['link'], player: data['player'], image: data['image'], source: data['source'], status: true)
        end
        # vs = get_viewers(data['viewers'])
        # game = Game.find_by(name: data['type'])
        # game.channels.create(title: data['title'], viewers: vs, link:data['link'], player: data['player'], image: data['image'], source: data['source'])
      end
    end

    update_threshold_time = update_begin_time - 200
    closed_channels = Channel.where("updated_at < ? AND status = ?", update_threshold_time, true)
    closed_channels.delete_all

    puts "All done!"
  end

  def self.init_db
    #names = ['DOTA2','英雄联盟','炉石传说','穿越火线','魔兽世界']
    games = {'DOTA2'=>'http://staticlive.douyutv.com/upload/game_cate/0d0ccaa16a0dc5ea4a4741a7e4433386.png','英雄联盟'=>'http://staticlive.douyutv.com/upload/game_cate/be8db394d66ec6f51c12d287141ff99e.jpg','炉石传说'=>'http://staticlive.douyutv.com/upload/game_cate/8be974233e4ac4cb8db246f3dc29e4d8.jpg','穿越火线'=>'http://staticlive.douyutv.com/upload/game_cate/fbf130f9ad4cb3c76190357b47cd1f23.png','魔兽世界'=>'http://staticlive.douyutv.com/upload/game_cate/644537f4bd14901732f01e1ab9d8322b.png'}
    games.each do |name,image|
      game = Game.find_by(name: name)
      Game.create(name: name,image: image) unless game
    end
  end

  def self.all_live_channels
    Channel.all.where(status: true)
  end


  def get_live_channels
    channels.where(status: true)
  end



  private

  def self.get_viewers (str)
    str.slice! '人'
    str.slice! ','
    if str.include? '万'
      str.slice! '万'
      str = str.to_f*10000
    end
    str.to_i
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    @channels = Game.all_live_channels.order(viewers: :desc).limit(8)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    game = Game.find_by_id params[:id]
    @channels = game.get_live_channels.order(viewers: :desc).limit(20)
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_data
    require "importio"
    client = Importio.new("c676d33a-07d7-46ef-8d08-a6920ea7daf6", "ToGGkRNT60bqadUUNW66knixXKB9uw8HwHCIDTQz8ocY1OBklyKXesXgYX1yUFooW4sMYgEG4WBqaTsQuT8j5w==")
    client.connect
    data_rows = []

    callback = lambda do |query, message|
      # Disconnect messages happen if we disconnect the client library while a query is in progress
      if message["type"] == "DISCONNECT"
        puts "The query was cancelled as the client was disconnected"
      end
      if message["type"] == "MESSAGE"
        if message["data"].key?("errorType")
          # In this case, we received a message, but it was an error from the external service
          puts "Got an error!"
          puts JSON.pretty_generate(message["data"])
        else
          # We got a message and it was not an error, so we can process the data
          puts "Got data!"
          #puts JSON.pretty_generate(message["data"])
          # Save the data we got in our dataRows variable for later
          data_rows << message["data"]["results"]
        end
      end
      if query.finished
        puts "Query finished"
      end
    end

    client.query({"input"=>{"query"=>"server"},"connectorGuids"=>["b0260b47-8da4-4ebb-84b0-67bc1d6a79bf"]}, callback)

    client.query({"input"=>{"query"=>"server"},"connectorGuids"=>["134b171b-c419-4cbb-9924-c952476c230a"]}, callback)
    client.join
    client.disconnect

    data_rows.each do |datas|
      datas.each do |data|
        channel = Channel.find_by(link: data['link'])
        vs = get_viewers(data['viewers'])
        if channel
          channel.update(title: data['title'], viewers: vs, player: data['player'], image: data['image'])
        else
          game = Game.find_by(name: data['type'])
          game.channels.create(title: data['title'], viewers: vs, link:data['link'], player: data['player'], image: data['image'], source: data['source'])
        end
      end
    end
    redirect_to root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end

  def get_viewers (str)
    str.slice! '人'
    str.slice! ','
    if str.include? '万'
      str.slice! '万'
      str = str.to_f*10000
    end
    str.to_i
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="channel-main">
  <script type="text/javascript" src="http://staticlive.douyutv.com/common/js/jquery.tinyscrollbar.min.js"></script>

  <%= render "shared/left_column" %>



  <div class="expandRight column" id="main_col">
    <div class="content">
      <div id="elem-mimiko-test" class="stretch js-columns-scroll scroll" style="top: 0px; bottom: 0px; visibility: visible;">
        <div class="tse-scroll-content" style="right: 0px; width: 1340px; height: 979px;">
          <div class="tse-content" style=" padding-right:0px;">
            <div class="player_column">
              <div class="editable editable01" id="broadcast_meta">
                <div class="info" style="padding-left:0;">
                  <div class="title"> <span class="real_title js-title">热门游戏</span> </div>
                </div>
              </div>
              <div class="items items01 clearfix" id="item_data"><ul>

                <% @games.each do |c| %>

                    <li class="unit">
                      <a  href="<%=  game_url c %>" class="thumb" title="<%=  c.name %>"><img class="preview" src="<%=  c.image %>" /></a>
                      <a  href="<%=  game_url c %>" class="title" style="border: 0px"><%=  c.name %></a>
                    </li>

                <% end %>


              </ul></div>

              <div class="editable editable01" id="broadcast_meta">
                <div class="info" style="padding-left:0;">
                  <div class="title"> <span class="real_title js-title">热门直播</span> </div>
                </div>
              </div>

              <div class="items items01 clearfix" id="item_data"><ul>

                <% @channels.each do |c| %>
                    <li><a href="<%=  c.link %>" target='_blank' class="list" title="<%=  c.title %>"><span class="img"><img src="<%=  c.image %>" onerror="this.src='http://staticlive.douyutv.com/upload/web_pic/default2_thumb.gif'; this.onerror = null;" width="320" height="180"/></span>
                      <div class="mes">
                        <h1 class="title"><%=  c.title %></h1>
                        <p class="moreMes"><span class="view"><%=  c.viewers %></span><span class="nnt"><%=  c.player %></span><span class="zbName"><em><%=  c.game.name %></em></span></p>
                      </div>
                      <i class="icon_live">正在直播</i> </a>
                    </li>
                <% end %>
              </ul></div>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="channel-main">
  <script type="text/javascript" src="http://staticlive.douyutv.com/common/js/jquery.tinyscrollbar.min.js"></script>

  <%= render "shared/left_column" %>



  <div class="expandRight column" id="main_col">
    <div class="content">
      <div id="elem-mimiko-test" class="stretch js-columns-scroll scroll" style="top: 0px; bottom: 0px; visibility: visible;">
        <div class="tse-scroll-content" style="right: 0px; width: 1340px; height: 979px;">
          <div class="tse-content" style=" padding-right:0px;">
            <div class="player_column">
              <div class="editable editable01" id="broadcast_meta">
                <div class="info" style="padding-left:0;">
                  <div class="title"> <span class="real_title js-title"><%= @game.name %></span> </div>
                </div>
              </div>
              <div class="items items01 clearfix" id="item_data"><ul>

                <% @channels.each do |c| %>
                    <li><a href="<%=  c.link %>" target='_blank' class="list" title="<%=  c.title %>"><span class="img"><img src="<%=  c.image %>" onerror="this.src='http://staticlive.douyutv.com/upload/web_pic/default2_thumb.gif'; this.onerror = null;" width="320" height="180"/></span>
                      <div class="mes">
                        <h1 class="title"><%=  c.title %></h1>
                        <p class="moreMes"><span class="view"><%=  c.viewers %></span><span class="nnt"><%=  c.player %></span><span class="zbName"><em><%=  c.source %></em></span></p>
                      </div>
                      <i class="icon_live">正在直播</i> </a>
                    </li>
                <% end %>


              </ul></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>